# Generated by Django 4.0.2 on 2022-03-07 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Task title')),
                ('description', models.TextField(blank=True, verbose_name='Note for task')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='When it mast be achieved')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of creating task')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Finish date')),
                ('deadline_is_matched', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('title',),
            },
        ),
    ]
